apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-rest-deployment
  labels:
    app: springboot-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-rest
  template:
    metadata:
      labels:
        app: springboot-rest
    spec:
      containers:
      - name: springboot-rest
        image: 070889/springboot-rest:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /api/hello
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/hello
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
